namespace BlazorElectronics.Server.Admin.Services;

public static class AdminProductData
{
    public static readonly string[] PRODUCT_TITLES =
        { "Book", "Software", "Video Game", "Movie/Tv", "Course" };
    public static readonly string[] PRODUCT_IMAGES =
        { "Book", "Software", "Video Game", "Movie/Tv", "Course" };
    public static readonly DateTime MIN_RELEASE_DATE = new();
    public static readonly DateTime MAX_RELEASE_DATE = DateTime.Now;
    public const int MAX_NUM_SOLD = 100000;
    public const decimal MAX_PRICE = 9999;
    public const float MAX_RATING = 5.0f;

    public const int MAX_PAGE_LENGTH = 1000;
    public const int MAX_AUDIO_LENGTH = 1000;

    public const int MAX_RUNTIME = 500;
    public const int MAX_EPISODES = 1000;

    public const int MAX_COURSE_DURATION = 500;
    
    public static readonly string[] NAMES =
    {
        "James Smith",
        "Maria Rodriguez",
        "Robert Johnson",
        "Linda Martinez",
        "Michael Brown",
        "Elizabeth Taylor",
        "William Jones",
        "Barbara Wilson",
        "David Lee",
        "Jennifer White",
        "Richard Harris",
        "Patricia Clark",
        "Joseph Young",
        "Sarah Lewis",
        "Charles Hall",
        "Lisa Allen",
        "Thomas Walker",
        "Nancy King",
        "Christopher Wright",
        "Susan Lopez",
        "Daniel Adams",
        "Margaret Green",
        "Matthew Hill",
        "Jessica Moore",
        "Anthony Scott",
        "Sandra Mitchell",
        "Brian Campbell",
        "Betty Carter",
        "Kevin Roberts",
        "Karen Rodriguez",
        "Laura Turner",
        "John Phillips",
        "Peter Evans",
        "Amanda Torres",
        "Justin Nelson",
        "Melissa Edwards",
        "Brandon Parker",
        "Stephanie Ross",
        "Gary Morgan",
        "Tina Perry",
        "Edward Powell",
        "Cynthia Coleman",
        "Jeffrey Sanchez",
        "Rebecca Rivera",
        "Gregory Cox",
        "Kathleen Howard",
        "Jerry Ward",
        "Shirley Brooks",
        "Walter Diaz",
        "Gloria Gray"
    };
    public static readonly string[] ISBNS =
    {
        "978-3-16-148410-0",
        "978-0-575-08358-1",
        "978-1-4028-9462-6",
        "978-0-596-52068-7",
        "978-0-306-40615-7",
        "978-3-540-49698-4",
        "978-0-387-95041-9",
        "978-1-891830-85-3",
        "978-1-60309-047-6",
        "978-0-345-54288-5",
        "978-0-671-72706-1",
        "978-1-4516-2178-2",
        "978-0-7432-7356-0",
        "978-0-141-18436-1",
        "978-0-8135-2905-4",
        "978-0-425-21256-8",
        "978-0-312-93921-9",
        "978-0-307-29152-0",
        "978-0-7434-4620-4",
        "978-0-684-85636-2",
        "978-0-06-112241-5",
        "978-0-394-58048-5",
        "978-0-345-47250-1",
        "978-0-689-86746-0",
        "978-0-553-38280-2",
        "978-0-307-26575-3",
        "978-0-446-57980-3",
        "978-0-14-017739-8",
        "978-0-06-083865-2",
        "978-0-7615-3643-7"
    };
    public static readonly string[] PUBLISHERS =
    {
        "Penguin Random House",
        "HarperCollins",
        "Simon & Schuster",
        "Hachette Book Group",
        "Macmillan Publishers",
        "Scholastic Inc.",
        "Wiley (John Wiley & Sons)",
        "McGraw-Hill Education",
        "Pearson Education",
        "Elsevier",
        "Oxford University Press",
        "Springer Nature",
        "Cengage Learning",
        "Taylor & Francis",
        "SAGE Publications",
        "Bloomsbury",
        "Routledge",
        "Cambridge University Press",
        "Thomson Reuters",
        "Houghton Mifflin Harcourt",
        "Kodansha",
        "Shueisha",
        "Klett Gruppe",
        "Planeta Group",
        "Bonnier Books",
        "Bertelsmann",
        "Wolters Kluwer",
        "Random House Publishing Group",
        "Chronicle Books",
        "Zondervan"
    };
    public static readonly string[] DIRECTORS =
    {
        "Steven Spielberg",
        "Martin Scorsese",
        "Alfred Hitchcock",
        "Christopher Nolan",
        "Quentin Tarantino",
        "Ridley Scott",
        "James Cameron",
        "David Fincher",
        "Stanley Kubrick",
        "Peter Jackson",
        "Francis Ford Coppola",
        "Guillermo del Toro",
        "Tim Burton",
        "Spike Lee",
        "Wes Anderson",
        "J.J. Abrams",
        "Michael Bay",
        "Kathryn Bigelow",
        "Clint Eastwood",
        "Ron Howard",
        "David Lynch",
        "George Lucas",
        "Sam Mendes",
        "Hayao Miyazaki",
        "Tyler Perry",
        "Guy Ritchie",
        "Oliver Stone",
        "Denis Villeneuve",
        "John Woo",
        "Zack Snyder"
    };
    public static readonly string[] ACTORS =
    {
        "Tom Hanks",
        "Meryl Streep",
        "Leonardo DiCaprio",
        "Denzel Washington",
        "Sandra Bullock",
        "Brad Pitt",
        "Julia Roberts",
        "George Clooney",
        "Angelina Jolie",
        "Johnny Depp",
        "Robert De Niro",
        "Kate Winslet",
        "Morgan Freeman",
        "Scarlett Johansson",
        "Russell Crowe",
        "Nicole Kidman",
        "Christian Bale",
        "Cate Blanchett",
        "Daniel Day-Lewis",
        "Emma Stone",
        "Will Smith",
        "Natalie Portman",
        "Matt Damon",
        "Anne Hathaway",
        "Tom Cruise",
        "Jennifer Lawrence",
        "Hugh Jackman",
        "Charlize Theron",
        "Ryan Gosling",
        "Amy Adams",
        "Joaquin Phoenix",
        "Viola Davis",
        "Mark Wahlberg",
        "Marion Cotillard",
        "Chris Hemsworth",
        "Jessica Chastain",
        "James McAvoy",
        "Margot Robbie",
        "Idris Elba",
        "Naomi Watts",
        "Benedict Cumberbatch",
        "Emily Blunt",
        "Robert Downey Jr.",
        "Rachel McAdams",
        "Jake Gyllenhaal",
        "Lupita Nyong'o",
        "Jeremy Renner",
        "Reese Witherspoon",
        "Michael Fassbender",
        "Saoirse Ronan"
    };
    public static readonly string[] SOFTWARE_VERSIONS =
    {
        "1.0.0",
        "1.0.1",
        "1.1.0",
        "1.2.3",
        "2.0.0",
        "2.1.0",
        "2.1.1",
        "2.2.0",
        "3.0.0",
        "3.0.1",
        "3.1.0",
        "3.1.5",
        "4.0.0",
        "4.1.0",
        "4.1.2",
        "4.2.0",
        "5.0.0",
        "5.1.0",
        "5.1.3",
        "5.2.0",
        "6.0.0",
        "6.1.0",
        "6.1.4",
        "6.2.0",
        "7.0.0",
        "7.1.0",
        "7.1.1",
        "7.2.0",
        "8.0.0",
        "8.1.0"
    };
    public static readonly string[] SOFTWARE_DEVELOPERS =
    {
        "Bill Gates",
        "Mark Zuckerberg",
        "Jeff Bezos",
        "Larry Page",
        "Sergey Brin",
        "Steve Wozniak",
        "Tim Berners-Lee",
        "Linus Torvalds",
        "Guido van Rossum",
        "Bjarne Stroustrup",
        "Ken Thompson",
        "Brian Kernighan",
        "Dennis Ritchie",
        "Richard Stallman",
        "John Carmack",
        "James Gosling",
        "Marc Andreessen",
        "Anders Hejlsberg",
        "Steve Jobs",
        "Elon Musk",
        "Satya Nadella",
        "Sundar Pichai",
        "Ben Silbermann",
        "Rasmus Lerdorf",
        "Jack Dorsey",
        "Evan Spiegel",
        "Reed Hastings",
        "Mitchell Baker",
        "Gabe Newell",
        "Tommy Refenes"
    };
    public static readonly string[] GAME_DEVELOPERS =
    {
        "Nintendo",
        "Valve Corporation",
        "Rockstar Games",
        "Electronic Arts",
        "Activision Blizzard",
        "Ubisoft",
        "Square Enix",
        "Bethesda Game Studios",
        "Capcom",
        "Bungie",
        "Konami",
        "Epic Games",
        "CD Projekt Red",
        "Naughty Dog",
        "FromSoftware",
        "BioWare",
        "BANDAI NAMCO Entertainment",
        "343 Industries",
        "Infinity Ward",
        "Sony Santa Monica",
        "Insomniac Games",
        "SEGA",
        "Blizzard Entertainment",
        "Treyarch",
        "Riot Games",
        "Supercell",
        "Mojang Studios",
        "Rare",
        "Obsidian Entertainment",
        "Respawn Entertainment"
    };
    public static readonly string[] SOFTWARE_DEPENDENCIES =
    {
        "Newtonsoft.Json",
        "Entity Framework",
        "xUnit",
        "NUnit",
        "Moq",
        "log4net",
        "NLog",
        "AutoMapper",
        "Dapper",
        "ASP.NET MVC",
        "jQuery",
        "React",
        "Angular",
        "Vue.js",
        "Bootstrap",
        "Node.js",
        "Express",
        "Spring Framework",
        "Hibernate",
        "TensorFlow",
        "PyTorch",
        "Pandas",
        "NumPy",
        "Ruby on Rails",
        "Flask",
        "Django",
        "Laravel",
        "Symfony",
        "PHPUnit",
        "Apache Commons"
    };
    public static readonly string[] SOFTWARE_TRIAL_LIMITATIONS =
    {
        "Time-Limited Usage",
        "Feature-Limited Access",
        "Limited Output Quality",
        "Watermark on Output",
        "Limited Data Export",
        "Limited Number of Uses",
        "Nag Screens",
        "Limited Support",
        "Restricted File Saving",
        "Limited Number of Records"
    };
    public static readonly string[] COURSE_REQUIREMENTS =
    {
        "Basic Understanding of Subject Matter",
        "Access to a Computer",
        "Internet Connectivity",
        "Specific Software Installation",
        "Prior Course Completion",
        "Textbooks or Course Materials",
        "Functional Webcam and Microphone",
        "Active Participation",
        "Completion of Pre-course Assessment",
        "Minimum Age Requirement",
        "Proficiency in Course Language",
        "Time Commitment for Duration of Course",
        "Registration or Enrollment in Institution",
        "Specific Operating System",
        "Access to a Scientific Calculator",
        "Required Reading Before Course Start",
        "Updated Web Browser",
        "Learning Management System Access",
        "Payment of Course Fee",
        "Signed Student Agreement"
    };
}